user:
  name_max_len: 50
  pwd_min_len: 6
  email_max_len: 100
  phone_max_len: 40
 
product:
  img_max_size: 200
  per_page: 8
  img_max_size_cart: 50

order:
  per_page: 6
  shipping_cost_default: 40000

date_format: "%m/%d/%Y %H:%M"
